import Link from "next/link"
import { ArrowRight, MessageCircle } from "lucide-react"
import { PublicCard, PublicInfoPage } from "../public-shell"

export default async function SupportPage({ params }: { params: Promise<{ guildId: string }> }) {
  const { guildId } = await params
  return <>
    <PublicInfoPage guildId={guildId} eyebrow="SUPPORT CENTER" title="Need a hand? Start here." description="Find the right path for account questions, match issues, community guidance, and everything around the climb." cards={[{ label: "ACCOUNT", title: "Profiles and registration.", body: "Get help linking your player identity, finding your profile, or understanding what appears on the public leaderboard." }, { label: "MATCHES", title: "Results and disputes.", body: "If a game result looks wrong or a queue issue needs attention, collect the match details and send them to the team." }, { label: "COMMUNITY", title: "Ask where players are.", body: "Join the community channels for quick answers, queue coordination, event updates, and network announcements." }, { label: "STATUS", title: "See what is live.", body: "Season status, recent games, and current rankings are always available through the public portal." }]} />
    <section className="mx-auto max-w-[95rem] px-5 pb-16 sm:px-8"><PublicCard className="flex flex-col gap-5 border-cyan-300/15 bg-cyan-300/[0.04] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><div className="rounded-xl border border-cyan-300/20 bg-cyan-300/10 p-3 text-cyan-200"><MessageCircle className="size-5" /></div><div><p className="font-mono text-[10px] tracking-[.2em] text-cyan-300">{"// FASTEST RESPONSE"}</p><h2 className="mt-2 text-xl font-black">Questions? Join the Discord.</h2><p className="mt-1 max-w-xl text-sm leading-6 text-white/50">The community can help with account setup, match questions, queue coordination, and announcements.</p></div></div><Link href="https://discord.com" target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-cyan-300 px-4 py-3 text-sm font-bold text-slate-950 transition-transform hover:-translate-y-0.5">Join Discord <ArrowRight className="size-4" /></Link></PublicCard></section>
  </>
}
