import { ArrowUpRight, ChevronDown, Globe2, ShieldCheck, Users } from "lucide-react"
import { PublicCard, SectionHeading } from "../public-shell"

const partners = [
  { name: "CAPEly", type: "COMMUNITY", detail: "A focused home for competitive players and event nights.", accent: "cyan", tags: ["Website", "Discord"] },
  { name: "Dewier's Dungeon", type: "CREATOR HUB", detail: "A creator-led space for guides, VOD reviews, and custom challenges.", accent: "amber", tags: ["Discord", "Events"] },
  { name: "MC C.A.P.E.S", type: "SERVER NETWORK", detail: "Building welcoming spaces for players at every level of the climb.", accent: "violet", tags: ["Website", "Discord"] },
  { name: "Prodigy", type: "TEAM", detail: "A competitive roster pushing sharper practice and better matches.", accent: "emerald", tags: ["Discord", "Roster"] },
  { name: "Tier.Net", type: "TOOLS", detail: "Useful community tools for tracking, comparing, and improving.", accent: "cyan", tags: ["Website"] },
  { name: "TierTests", type: "EVENTS", detail: "Structured tests and community rankings that keep the meta moving.", accent: "amber", tags: ["Website", "1.8", "1.9+"] },
]

export default function PartnersPage() {
  return <main className="mx-auto max-w-[95rem] px-5 py-14 sm:px-8 sm:py-24"><SectionHeading eyebrow="COMMUNITY PARTNERS" title="Our partners." description="The communities, teams, and builders helping make competitive play more open, useful, and fun." /><div className="mx-auto mt-12 grid max-w-6xl gap-4 md:grid-cols-2 lg:grid-cols-3">{partners.map((partner) => <PublicCard key={partner.name} className="group overflow-hidden p-5"><div className={`mb-5 h-28 rounded-xl bg-gradient-to-br ${partner.accent === "cyan" ? "from-cyan-300/25 via-cyan-400/5" : partner.accent === "amber" ? "from-amber-300/25 via-amber-400/5" : partner.accent === "violet" ? "from-violet-300/25 via-violet-400/5" : "from-emerald-300/25 via-emerald-400/5"} to-transparent p-4`}><div className="flex h-full items-end justify-between"><span className="grid size-11 place-items-center rounded-full border border-white/15 bg-black/20 text-lg font-black text-white">{partner.name[0]}</span><ArrowUpRight className="size-4 text-white/40 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-white" /></div></div><p className="font-mono text-[10px] tracking-[.18em] text-cyan-300">{partner.type}</p><h2 className="mt-2 text-lg font-bold">{partner.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-white/45">{partner.detail}</p><div className="mt-4 flex flex-wrap gap-2">{partner.tags.map((tag) => <span key={tag} className="rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-[10px] font-semibold text-white/55">{tag}</span>)}</div><button className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-white/65 hover:text-cyan-200"><Globe2 className="size-3.5" /> Explore partner <ArrowUpRight className="size-3" /></button></PublicCard>)}</div><div className="mx-auto mt-8 flex max-w-6xl items-center justify-between gap-4 rounded-xl border border-white/[0.08] bg-white/[0.025] p-5"><div><p className="font-mono text-[10px] tracking-[.18em] text-amber-300">// PARTNER WITH US</p><p className="mt-2 text-sm text-white/55">Bring your community, event, or tool to the network.</p></div><button className="shrink-0 rounded-lg bg-white px-4 py-2.5 text-xs font-black text-[#071016]">Start a conversation</button></div></main>
}
