import Link from "next/link"
import { ArrowRight, ChevronRight, Gamepad2, Trophy, Users, Zap } from "lucide-react"
import { PublicCard, SectionHeading } from "./public-shell"
import { guildDisplayName, publicGames, publicPlayers, publicStats } from "./data"

export default async function PublicHome({ params }: { params: Promise<{ guildId: string }> }) {
  const { guildId } = await params
  const base = `/public/${guildId}`
  return <div>
    <section className="relative overflow-hidden"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_75%_25%,rgba(34,211,238,.14),transparent_32%),radial-gradient(circle_at_15%_60%,rgba(124,58,237,.11),transparent_28%)]" /><div className="public-enter relative mx-auto grid max-w-[95rem] gap-12 px-5 pb-20 pt-24 sm:px-8 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:pb-28 lg:pt-32"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/[0.06] px-3 py-1.5 font-mono text-[10px] tracking-wider text-cyan-200"><Zap className="size-3" /> SEASON 14 IS LIVE</div><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-0.06em] sm:text-7xl">Play sharper.<br /><span className="text-cyan-300">Climb higher.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/55">{guildDisplayName(guildId)} is a competitive home for players who want fair matchmaking, clean stats, and games worth remembering.</p><div className="mt-9 flex flex-wrap gap-3"><Link href={`${base}/leaderboard`} className="flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-[#071016] transition-transform hover:-translate-y-1">View leaderboard <ArrowRight className="size-4" /></Link><Link href={`${base}/players`} className="rounded-xl border border-white/15 px-5 py-3 text-sm font-bold text-white/80 transition-colors hover:bg-white/[0.08]">Meet the players</Link></div></div><PublicCard className="relative overflow-hidden p-6"><div className="absolute -right-14 -top-14 size-40 rounded-full bg-cyan-400/10 blur-3xl" /><div className="mb-7 flex items-center justify-between"><span className="font-mono text-[10px] tracking-[.2em] text-white/45">COMMUNITY STATUS</span><span className="flex items-center gap-2 font-mono text-[10px] text-emerald-300"><i className="size-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_#34d399]" /> COMMUNITY ONLINE</span></div><div className="grid grid-cols-2 gap-3">{publicStats.map(([label, value]) => <div key={label} className="rounded-xl bg-black/20 p-4"><p className="font-mono text-[10px] text-white/35">{label}</p><p className="mt-2 text-2xl font-black tracking-tight">{value}</p></div>)}</div><div className="mt-4 flex items-center gap-3 rounded-xl border border-white/[0.07] p-3"><div className="grid size-8 place-items-center rounded-lg bg-violet-400/15 text-violet-300"><Trophy className="size-4" /></div><div><p className="text-xs font-bold">Ranked matchmaking</p><p className="font-mono text-[10px] text-white/40">Average queue: 00:18</p></div></div></PublicCard></div></section>
    <section className="mx-auto max-w-[95rem] px-5 pb-20 sm:px-8"><SectionHeading eyebrow="YOUR COMMUNITY" title="Everything you need to compete." description="Follow the action, check your numbers, and find your next challenge." /><div className="grid gap-4 md:grid-cols-3">{[["Players", "Browse the community and find the names shaping the season.", Users, "/players"], ["Games", "Track recent matches, modes, maps, and results.", Gamepad2, "/games"], ["Leaderboard", "See who is leading the network across every ranked queue.", Trophy, "/leaderboard"]].map(([title, desc, Icon, href]) => <Link href={`${base}${href}`} key={title as string}><PublicCard className="group h-full p-6 transition-transform hover:-translate-y-1"><div className="mb-9 flex justify-between"><span className="grid size-10 place-items-center rounded-xl bg-white/[0.07] text-cyan-300"><Icon className="size-5" /></span><ChevronRight className="size-4 text-white/25 transition-transform group-hover:translate-x-1" /></div><h3 className="text-xl font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-white/45">{desc as string}</p></PublicCard></Link>)}</div></section>
    <section className="mx-auto max-w-[95rem] px-5 pb-24 sm:px-8"><PublicCard className="overflow-hidden p-6 sm:p-8"><div className="mb-6 flex items-end justify-between"><div><p className="font-mono text-[10px] tracking-[.2em] text-cyan-300">MATCH ACTIVITY</p><h2 className="mt-2 text-2xl font-black">Latest games</h2></div><Link href={`${base}/games`} className="text-xs font-bold text-cyan-300">View all <ArrowRight className="ml-1 inline size-3" /></Link></div><div className="divide-y divide-white/[0.07]">{publicGames.slice(0, 3).map(game => <div key={game.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><span className="font-mono text-xs text-white/35">{game.id}</span><span className="ml-4 text-sm font-bold">{game.winner}</span><span className="ml-3 rounded bg-white/[0.06] px-2 py-1 font-mono text-[10px] text-white/45">{game.mode}</span></div><div className="flex items-center gap-5 font-mono text-xs"><span className="text-white/60">{game.score}</span><span className="text-white/30">{game.time}</span></div></div>)}</div></PublicCard></section>
  </div>
}
