"use client"

import Link from "next/link"
import { ArrowUpRight, Gamepad2, Search, SlidersHorizontal } from "lucide-react"
import { useMemo, useState } from "react"
import type { PublicGame, PublicPlayer } from "./data"
import { PublicCard } from "./public-shell"

const ranks = ["ALL RANKS", "MASTER", "DIAMOND", "PLATINUM", "GOLD"]

export function PlayerBrowser({ guildId, players }: { guildId: string; players: PublicPlayer[] }) {
  const [query, setQuery] = useState(""); const [rank, setRank] = useState("ALL RANKS"); const [sort, setSort] = useState("ELO")
  const filtered = useMemo(() => players.filter((player) => player.name.toLowerCase().includes(query.toLowerCase()) && (rank === "ALL RANKS" || player.rank === rank)).sort((a, b) => sort === "WINS" ? b.wins - a.wins : sort === "STREAK" ? b.streak - a.streak : b.elo - a.elo), [players, query, rank, sort])
  return <div><div className="mb-4 grid gap-3 rounded-2xl border border-white/[0.09] bg-white/[0.025] p-3 sm:grid-cols-[1fr_auto_auto] sm:items-center"><label className="flex min-w-0 items-center gap-3 rounded-xl border border-white/[0.08] bg-black/20 px-3 py-2"><Search className="size-4 shrink-0 text-white/35" /><input aria-label="Search players" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search players..." className="w-full bg-transparent text-sm text-white outline-none placeholder:text-white/30" /></label><label className="flex items-center gap-2 rounded-xl border border-white/[0.08] px-3 py-2 font-mono text-[10px] text-white/45"><SlidersHorizontal className="size-3.5" /><select aria-label="Filter by rank" value={rank} onChange={(event) => setRank(event.target.value)} className="bg-transparent text-cyan-300 outline-none">{ranks.map((option) => <option key={option} className="bg-[#0b1017]" value={option}>{option}</option>)}</select></label><select aria-label="Sort players" value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-xl border border-white/[0.08] bg-transparent px-3 py-2 font-mono text-[10px] text-cyan-300 outline-none"><option className="bg-[#0b1017]" value="ELO">SORT: ELO</option><option className="bg-[#0b1017]" value="WINS">SORT: WINS</option><option className="bg-[#0b1017]" value="STREAK">SORT: STREAK</option></select></div><PublicCard className="overflow-hidden"><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((player) => <Link key={player.id} href={`/public/${guildId}/players/${player.id}`} className="group rounded-xl border border-white/[0.07] bg-black/10 p-4 transition-all hover:-translate-y-0.5 hover:border-cyan-300/35 hover:bg-cyan-300/[0.04]"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-full bg-gradient-to-br from-cyan-300/30 to-violet-400/30 text-sm font-black text-cyan-100">{player.avatar}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="truncate text-sm font-bold">{player.name}</h3><ArrowUpRight className="size-4 text-white/25" /></div><p className="mt-1 font-mono text-[10px] tracking-wider text-cyan-300">{player.rank}</p></div></div><div className="mt-5 grid grid-cols-3 gap-2 border-t border-white/[0.07] pt-3 text-center"><div><p className="font-mono text-[10px] text-white/35">ELO</p><p className="mt-1 text-sm font-bold">{player.elo}</p></div><div><p className="font-mono text-[10px] text-white/35">WINS</p><p className="mt-1 text-sm font-bold">{player.wins}</p></div><div><p className="font-mono text-[10px] text-white/35">STREAK</p><p className="mt-1 text-sm font-bold text-emerald-300">{player.streak}W</p></div></div></Link>)}</div>{filtered.length === 0 && <p className="p-10 text-center text-sm text-white/45">No players match those filters.</p>}</PublicCard></div>
}

export function GameBrowser({ games }: { games: PublicGame[] }) { const [query, setQuery] = useState(""); const [mode, setMode] = useState("ALL MODES"); const modes = ["ALL MODES", ...Array.from(new Set(games.map((game) => game.mode)))]; const filtered = games.filter((game) => `${game.id} ${game.map} ${game.winner}`.toLowerCase().includes(query.toLowerCase()) && (mode === "ALL MODES" || game.mode === mode)); return <div><div className="mb-4 grid gap-3 rounded-2xl border border-white/[0.09] bg-white/[0.025] p-3 sm:grid-cols-[1fr_auto] sm:items-center"><label className="flex items-center gap-3 rounded-xl border border-white/[0.08] bg-black/20 px-3 py-2"><Search className="size-4 text-white/35" /><input aria-label="Search games" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search maps, players, match IDs..." className="w-full bg-transparent text-sm text-white outline-none placeholder:text-white/30" /></label><select aria-label="Filter games by mode" value={mode} onChange={(event) => setMode(event.target.value)} className="rounded-xl border border-white/[0.08] bg-transparent px-3 py-2 font-mono text-[10px] text-cyan-300 outline-none">{modes.map((option) => <option key={option} className="bg-[#0b1017]" value={option}>{option}</option>)}</select></div><PublicCard className="overflow-hidden"><div className="grid grid-cols-[1fr_auto_auto] gap-4 border-b border-white/[0.08] px-5 py-4 font-mono text-[10px] tracking-wider text-white/35"><span>MATCH</span><span>RESULT</span><span>WHEN</span></div><div className="divide-y divide-white/[0.07]">{filtered.map((game) => <div key={game.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 px-5 py-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-cyan-300/10 text-cyan-300"><Gamepad2 className="size-4" /></span><div><p className="font-mono text-xs text-white/40">{game.id} · {game.mode}</p><p className="mt-1 text-sm font-bold">{game.map}</p></div></div><div className="text-right"><p className="text-sm font-bold text-emerald-300">{game.winner}</p><p className="mt-1 font-mono text-xs text-white/45">{game.score}</p></div><span className="text-right font-mono text-[11px] text-white/35">{game.time}</span></div>)}</div>{filtered.length === 0 && <p className="p-10 text-center text-sm text-white/45">No games match those filters.</p>}</PublicCard></div> }

export function PublicSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="flex items-center gap-2 rounded-xl border border-white/[0.08] px-3 py-2 font-mono text-[10px] text-white/45">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="bg-transparent text-cyan-300 outline-none">{options.map((option) => <option key={option} className="bg-[#0b1017]" value={option}>{option}</option>)}</select></label> }
