"use client"

import { ExternalLink, Play, Users, Video } from "lucide-react"
import { PublicCard, SectionHeading } from "../public-shell"

const creators = [
  { name: "WIGGLES", handle: "@wiggles", role: "OWNER", audience: "184K", focus: "Ranked breakdowns and live climb sessions", color: "from-cyan-300/25 via-cyan-400/5 to-transparent" },
  { name: "MAVEN", handle: "@mavenplays", role: "ANALYST", audience: "62K", focus: "Patch notes, VOD reviews, and meta reads", color: "from-amber-300/25 via-amber-400/5 to-transparent" },
  { name: "PRBW", handle: "@prbw", role: "COMMUNITY", audience: "38K", focus: "Tournament nights and community events", color: "from-violet-300/25 via-violet-400/5 to-transparent" },
]

export default function CreatorsPage() {
  return <main className="mx-auto max-w-[95rem] px-5 py-14 sm:px-8 sm:py-24"><SectionHeading eyebrow="CREATOR NETWORK" title="Watch the pros play." description="Learn from the players, analysts, and community voices turning every match into a better way to climb." /><div className="mx-auto mt-12 max-w-5xl space-y-5">{creators.map((creator, index) => <PublicCard key={creator.name} className={`relative overflow-hidden bg-gradient-to-br ${creator.color} p-6 sm:p-8`}><div className="absolute right-6 top-6 font-mono text-[10px] tracking-[.2em] text-white/25">0{index + 1} / FEATURED</div><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="grid size-28 shrink-0 place-items-center rounded-full border-4 border-cyan-200/70 bg-[#0c1621] text-4xl font-black text-cyan-200 shadow-[0_0_45px_rgba(34,211,238,.18)]">{creator.name[0]}</div><div className="min-w-0"><span className="rounded-full bg-white/80 px-3 py-1 text-[10px] font-black tracking-widest text-[#071016]">{creator.role}</span><h2 className="mt-4 text-3xl font-black tracking-tight text-white sm:text-4xl">{creator.name} <span className="text-base font-medium text-white/35">{creator.handle}</span></h2><div className="mt-3 flex flex-wrap gap-2 text-xs font-semibold text-white/60"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-black/20 px-3 py-2"><Users className="size-3.5 text-cyan-300" /> {creator.audience} audience</span><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-black/20 px-3 py-2"><Video className="size-3.5 text-amber-300" /> {creator.focus}</span></div><div className="mt-5 flex flex-wrap gap-2"><button className="inline-flex items-center gap-2 rounded-lg bg-cyan-300 px-4 py-2.5 text-xs font-black text-[#071016] transition hover:bg-cyan-200"><Play className="size-3.5 fill-current" /> Watch channel</button><button className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2.5 text-xs font-semibold text-white/60 hover:border-white/25 hover:text-white"><ExternalLink className="size-3.5" /> View profile</button></div></div></div></PublicCard>)}</div><PublicCard className="mx-auto mt-8 max-w-5xl p-6 text-center sm:p-8"><p className="font-mono text-[10px] tracking-[.2em] text-cyan-300">// CREATOR PERKS</p><h2 className="mt-3 text-xl font-bold">Build your audience around fair competition.</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-white/45">Creator partners get event access, season assets, profile spotlights, and a direct line to the community team.</p><button className="mt-5 rounded-lg border border-cyan-300/25 bg-cyan-300/10 px-4 py-2.5 text-xs font-bold text-cyan-200 hover:bg-cyan-300/15">Apply to the network</button></PublicCard></main>
}
